### ISSUE TITLE
ScrollArea issue when used inside Drawer/Dialog 

### ISSUE THREAD

**Issue by zirlman** [huybuidac/shadcn-datetime-picker#4]
The component is great, but I found an issue with the scrollable area when the DateTime picker is used inside [Drawer](https://ui.shadcn.com/docs/components/drawer) & [Dialog](https://ui.shadcn.com/docs/components/dialog) components. 

Below is a video demonstration
Drawer:
https://github.com/user-attachments/assets/ae58846c-59cb-4fff-8720-9f89234e24ad

Dialog:
https://github.com/user-attachments/assets/73b3d846-e12d-4f54-ba9d-b7db0a049cf5

Edit:
The Solution can be found here: https://github.com/radix-ui/primitives/issues/1159

For me, adding an event handler that calls `event.stopPropagation()` did the trick
```
<ScrollArea
     className="h-full flex-grow"
     onWheel={stopPropagation}     
     onTouchMove={stopPropagation}
> 
```

**Comment by huybuidac** [comment]
Thanks for pointing that out! I haven’t tested it on mobile yet—let me check.

**Comment by killian-dv** [comment]
I don't think the problem is that you're using it on mobile. It says in the [Radix documentation](https://www.radix-ui.com/primitives/docs/components/popover#root) that the popover must have the modal props set to true if used in a Dialog or Drawer. Just add this to your `datetime-picker.tsx` code and it should work.

`<Popover open={open} onOpenChange={setOpen} modal>`

**Comment by huybuidac** [comment]
Thank you! The issue should now be resolved.

https://shadcn-datetime-picker-pro.vercel.app/?path=/story/datetimepicker--inside-dialog

**Comment by tylerpashigian** [comment]
@killian-dv this solution resolved my issue on desktop but I am still having the issue on mobile. For context I am using shadcn and I have a popover nested in a combobox, which lives in a modal on desktop and a drawer on mobile. The `modal` prop is passed in as true for both use cases. Its the same component rendering the combobox, just a different parent component, and the issue is only with the drawer. Any thoughts?
